package ru.data.anonymization.tool.methods.options.type;

import lombok.Data;
import lombok.NoArgsConstructor;
import ru.data.anonymization.tool.methods.options.MaskItem;
import ru.data.anonymization.tool.service.DatabaseConnectionService;

import java.sql.Date;
import java.sql.ResultSet;
import java.util.List;

@Data
@NoArgsConstructor
public class DateAging implements MaskItem {
    private String nameTable;
    private String nameColumn;
    private int countDays;

    @Override
    public String getTable() {
        return nameTable;
    }

    @Override
    public List<String> getColumn() {
        return List.of(nameColumn);
    }

    @Override
    public void start(DatabaseConnectionService controllerDB) throws Exception {
        controllerDB.execute("ALTER TABLE " + nameTable + " ADD COLUMN masking_method_temp_id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE;");

        ResultSet resultSet = controllerDB.executeQuery("SELECT " + nameColumn + ", masking_method_temp_id FROM " + nameTable + ";");
        Date cur;
        while (resultSet.next()) {
            cur = resultSet.getDate(1);
            if (cur == null) {
                continue;
            }
            resultSet.updateDate(1, Date.valueOf(cur.toLocalDate().plusDays(countDays)));
            resultSet.updateRow();
        }
        controllerDB.execute("ALTER TABLE " + nameTable + " DROP COLUMN masking_method_temp_id;");
    }
}
