package ru.data.anonymization.tool.methods.options.type;

import java.sql.SQLException;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import ru.data.anonymization.tool.methods.options.MaskItem;
import ru.data.anonymization.tool.service.DatabaseConnectionService;

import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

@Data
@NoArgsConstructor
@Slf4j
public class Shuffle implements MaskItem {

    private String nameTable;
    private List<String> namesColumn;

    @Override
    public String getTable() {
        return nameTable;
    }

    @Override
    public List<String> getColumn() {
        return namesColumn;
    }

    private String convertListToString(List<String> strArr, String delimiter) {
        StringBuilder sb = new StringBuilder();
        for (String str : strArr) {
            sb.append(str).append(delimiter);
        }
        return sb.substring(0, sb.length() - 1);
    }

    @Override
    public void start(DatabaseConnectionService controllerDB) throws Exception {
        for (String columnsRow : namesColumn) {
            String newNameTable = "mixing_instructions_" + columnsRow;
            List<Integer> oldPosition = new ArrayList<>();
            List<Integer> newPosition = new ArrayList<>();

            controllerDB.execute("CREATE TABLE " + newNameTable
                                 + " (id SERIAL PRIMARY KEY,old_position INT,new_position INT);");
            controllerDB.execute("ALTER TABLE " + nameTable
                                 + " ADD COLUMN masking_id_for_shuffle INT GENERATED BY DEFAULT AS IDENTITY UNIQUE;");
            ResultSet resultSet = controllerDB.executeQuery(
                    "select count(*) from " + nameTable + ";");
            resultSet.next();
            int sizeTable = resultSet.getInt(1);
            resultSet = controllerDB.executeQuery(
                    "select " + columnsRow + ",masking_id_for_shuffle from " + nameTable + ";");

            while (resultSet.next()) {
                for (int k = 1; k <= 2; k++) {
                    log.debug(resultSet.getString(k));
                }
            }
            resultSet.beforeFirst();
            shuffling(sizeTable, resultSet, oldPosition, newPosition);
            controllerDB.execute(
                    "ALTER TABLE " + nameTable + " DROP COLUMN masking_id_for_shuffle;");

            for (int j = 0; j < oldPosition.size(); j++) {
                controllerDB.execute(
                        "INSERT INTO " + newNameTable + " (old_position,new_position) values("
                        + oldPosition.get(j) + ", " + newPosition.get(j) + ");");
            }
        }

    }

    private void shuffling(
            int sizeTable,
            ResultSet resultSet,
            List<Integer> oldPosition,
            List<Integer> newPosition) throws SQLException {
        int cur;
        Object buf1;
        Object buf2;
        Random random = new Random();
        for (int i = sizeTable; i >= 2; i--) {
            cur = random.nextInt(i - 1) + 1;
            log.debug(String.valueOf(cur));

            for (int j = 1; j < 2; j++) {
                resultSet.absolute(cur);
                buf1 = resultSet.getObject(j);

                resultSet.absolute(i);
                buf2 = resultSet.getObject(j);

                resultSet.updateObject(j, buf1);
                resultSet.updateRow();

                resultSet.absolute(cur);
                resultSet.updateObject(j, buf2);
                resultSet.updateRow();

                oldPosition.add(cur);
                newPosition.add(i);
            }
            resultSet.beforeFirst();
            log.info("{old id : {}, new id : {}}", cur, i);
            int count = 1;
            while (resultSet.next()) {
                for (int k = 1; k < 2; k++) {
                    log.info("{} , {}", resultSet.getString(k), count);
                }
                count++;
            }
            resultSet.beforeFirst();
        }
    }

}
