package ru.data.anonymization.tool.methods.options.type;

import lombok.Data;
import lombok.NoArgsConstructor;
import ru.data.anonymization.tool.methods.options.MaskItem;
import ru.data.anonymization.tool.service.DatabaseConnectionService;

import java.sql.Date;
import java.sql.ResultSet;
import java.util.List;
import java.util.Random;

@Data
@NoArgsConstructor
public class ValueVariance implements MaskItem {

    private String nameTable;
    private String nameColumn;
    private int sigma;
    private DataType dataType;

    public enum DataType {
        INTEGER, FLOAT, DATE
    }

    @Override
    public String getTable() {
        return nameTable;
    }

    @Override
    public List<String> getColumn() {
        return List.of(nameColumn);
    }

    @Override
    public void start(DatabaseConnectionService controllerDB) throws Exception {
        controllerDB.execute("ALTER TABLE " + nameTable
                             + " ADD COLUMN masking_method_temp_id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE;");
        ResultSet resultSet = controllerDB.executeQuery(
                "SELECT " + nameColumn + ", masking_method_temp_id FROM " + nameTable + ";");
        Random random = new Random();
        switch (dataType) {
            case INTEGER -> {
                while (resultSet.next()) {
                    int cur = resultSet.getInt(1);
                    int per = (int)random.nextGaussian() * sigma;
                    resultSet.updateInt(1, cur + per);
                    resultSet.updateRow();
                }
            }
            case FLOAT -> {
                while (resultSet.next()) {
                    double cur = resultSet.getDouble(1);
                    double per = random.nextGaussian() * sigma;
                    resultSet.updateDouble(1, cur + per);
                    resultSet.updateRow();
                }
            }
            case DATE -> {
                while (resultSet.next()) {
                    Date cur = resultSet.getDate(1);
                    if (cur == null) {
                        continue;
                    }
                    int per = (int)random.nextGaussian() * sigma;
                    int day = cur.toLocalDate().getDayOfMonth();
                    int month = cur.toLocalDate().getMonthValue();

                    day -= day - ((day * per) / 100);
                    month -= month - ((month * per) / 100);
                    resultSet.updateDate(1,
                                         Date.valueOf(cur.toLocalDate()
                                                         .plusDays(day)
                                                         .plusMonths(month))
                    );
                    resultSet.updateRow();
                }
            }
        }

        controllerDB.execute("ALTER TABLE " + nameTable + " DROP COLUMN masking_method_temp_id;");
    }

}
